deployment:
  tasks:
    - export DEPLOYPATH=/home/ifthesel/cms/
    - /bin/cp -R api $DEPLOYPATH
    - /bin/cp -R components $DEPLOYPATH
    - /bin/cp -R config $DEPLOYPATH
    - /bin/cp -R extensions $DEPLOYPATH
    - /bin/cp -R public $DEPLOYPATH
    - /bin/cp package.json $DEPLOYPATH
